CREATE TABLE posts (
  id INT(255) NOT NULL PRIMARY KEY AUTO_INCREMENT,
  uid INT(255) NOT NULL,
  title VARCHAR(255) NOT NULL,
  location VARCHAR(255) NOT NULL,
  description TEXT NOT NULL,
  pic TEXT NULL DEFAULT NULL
);
